"$schema" = 'https://starship.rs/config-schema.json'

[terraform]
disabled = false

[aws]
disabled = true

[directory]
read_only = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
