#!/bin/env python3

import subprocess
import shlex
import sys
import random
import os
from io import BytesIO

import boto3
import pyperclip

BUCKET_NAME = "files-rileyflynn-me"
URL_PATH_PREFIX = "https://i.worldsgreatestpython.dev/"

out = subprocess.run(shlex.split("flameshot gui -r"), capture_output=True)
if out.returncode == 0:
    with open(os.path.expanduser("~/.scripts/adjectives")) as f:
        adjectives = list(map(lambda x: x.rstrip("\n"), f.readlines()))
    with open(os.path.expanduser("~/.scripts/animals")) as f:
        animals = list(map(lambda x: x.rstrip("\n"), f.readlines()))
    filename = f"{'-'.join(random.choice(adjectives) for _ in range(2))}"
    filename += f"-{random.choice(animals)}.png"

    screenshot = BytesIO(out.stdout)

    s3_client = boto3.client("s3")
    s3_client.upload_fileobj(
        screenshot,
        BUCKET_NAME,
        filename,
        ExtraArgs={"ACL": "public-read", "ContentType": "image/png"},
    )

    pyperclip.copy(f"{URL_PATH_PREFIX}{filename}")

else:
    sys.exit(out.returncode)
